### ISSUE TITLE
🛑 Website is down

### ISSUE THREAD

**Issue by thecoder876** [SimpleEdit/status#1]
In [`b845536`](https://github.com/SimpleEdit/status/commit/b845536eba4c60e9e66ade43533d193b7b7382bc
), Website (https://simpleedit.github.io) was **down**:
- HTTP code: 404
- Response time: 90 ms

**Comment by wgyt** [comment]
uhhh I forgot to change the url 🤦🏻

**Comment by thecoder876** [comment]
> uhhh I forgot to change the url 🤦🏻

@wgyt seriously?
